# Generated by Django 4.1.3 on 2022-12-01 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='url_http_link',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
