# Generated by Django 4.1.3 on 2022-12-01 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0004_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutABC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'AboutABC',
            },
        ),
    ]
