# Generated by Django 4.1.3 on 2022-12-01 05:03

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0006_remove_aboutabc_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutabc',
            name='description',
            field=ckeditor.fields.RichTextField(default='xyz'),
        ),
    ]
