# Generated by Django 4.1.3 on 2022-12-18 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paymentapp', '0001_initial'),
        ('store_app', '0010_cartproduct_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='paymentapp.checkout'),
        ),
    ]
