# Generated by Django 4.1.3 on 2022-12-18 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='payment_option',
            field=models.CharField(blank=True, choices=[('Cash on Delivery', 'Cash on Delivery'), ('Bkash', 'Bkash')], max_length=150, null=True),
        ),
    ]
