# Generated by Django 4.1.3 on 2022-12-20 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paymentapp', '0002_checkout_payment_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='payment_option',
        ),
    ]
