# Generated by Django 4.1.3 on 2022-12-29 03:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paymentapp', '0003_remove_checkout_payment_option'),
    ]

    operations = [
        migrations.CreateModel(
            name='BkashPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentID', models.CharField(max_length=150)),
                ('createTime', models.CharField(max_length=150)),
                ('orgName', models.CharField(max_length=150)),
                ('transactionStatus', models.CharField(max_length=150)),
                ('amount', models.CharField(max_length=150)),
                ('currency', models.CharField(max_length=150)),
                ('intent', models.CharField(max_length=150)),
                ('merchantInvoiceNumber', models.CharField(max_length=150)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BkashPayment',
                'verbose_name_plural': 'BkashPayments',
            },
        ),
    ]
